ACCOUNT_NAMES = [
    'Allie Oppps',
    'Alley Kats',
    'Allie\'s Cats ',
    'Cat House',
    'Believe it!',
    'Or Not?',
    'Rest In Peace',
    'Rest in Peas',
    'Best in Peas',
    'Bedrest',
    'Best in show',
    '@ House',
    '@ Space',
    'Dreams of Ice Cream ',
    'My Dear Aunt Sally',
    'My Fear is Fried Food',
    'And the winner is...',
    'Lick your chops',
    'Meat and Potatoes',
    'Tofu and Potatoes',
    'Alice\'s Malice',
    'Fake House',
    'Real House',
    'Surreal House',
    'Eat Your Vegetables',
    'Zip Zap ',
    'Shoe String',
    'Eat Your Peas!!',
    'Vegan, Shegan',
    'Our Name is Longer Than Your House Name',
    'Are You Hungry?',
]
